services:
  _defaults:
    autowire: true
    bind:
      $organisation: '%env(string:GIT_ORGANISATION)%'
      $authToken: '%env(string:AUTH_TOKEN)%'

  _instanceof:
    Symfony\Component\EventDispatcher\EventSubscriberInterface:
      tags: ['kernel.event_subscriber']

  App\:
    resource: '../src/*'
    exclude: '../src/{ValueObject,Kernel.php}'

  Github\Client:
    factory: '@App\Github\ClientFactory'

  App\Command\PullRequestCommand:
    tags:
      - { name: console.command, command: stats:pullrequests}
      - { name: console.command, command: stats:pr}